label: 配置手册
pages:
    - label: 介绍
      url: /config-guide/bk-config-guide.html

    - label: 安全设置
      url: /config-guide/secy/secy.html
      children:
        - label: 确保cron.php文件在浏览器上的安全
          url: /config-guide/secy/secy-cron.html

        - label: X-Frame-Options头
          url: /config-guide/secy/secy-xframe.html

        - label: 防止缓存中毒
          url: /config-guide/secy/secy-headers.html

    - label: Magento初始化和引导
      url: /config-guide/bootstrap/magento-bootstrap.html
      children:

        - label: 设置引导参数
          url: /config-guide/bootstrap/magento-how-to-set.html

        - label: 关于Magento的模式
          url: /config-guide/bootstrap/magento-modes.html

        - label: 自定义基础目录路径(MAGE_DIRS)
          url: /config-guide/bootstrap/mage-dirs.html

        - label: 开启扼要记录(MAGE_PROFILER)
          url: /config-guide/bootstrap/mage-profiler.html

    - label: 管道部署
      versions: ["2.2", "2.3"]
      url: /config-guide/deployment/
      children:

        - label: Overview
          url: /config-guide/deployment/pipeline/

        - label: 技术细节
          url: /config-guide/deployment/pipeline/technical-details.html

        - label: 开发系统设置
          url: /config-guide/deployment/pipeline/development-system.html

        - label: 构建系统设置
          url: /config-guide/deployment/pipeline/build-system.html

        - label: 生产系统设置
          url: /config-guide/deployment/pipeline/production-system.html

        - label: 文件系统访问权限
          url: /config-guide/prod/prod_file-sys-perms.html

        - label: Examples
          children:

            - label: 共享配置
              url: /config-guide/deployment/pipeline/example/shared-configuration.html

            - label: 使用命令行命令
              url: /config-guide/deployment/pipeline/example/cli.html

            - label: 使用环境变量
              url: /config-guide/deployment/pipeline/example/environment-variables.html

            - label: 使用rsync同步命令
              url: /config-guide/deployment/pipeline/example/rsync.html

    - label: 单机部署
      versions: ["2.2", "2.3"]
      url: /config-guide/deployment/single-machine.html

    - label: 命令行配置
      url: /config-guide/cli/config-cli.html
      children:

        - label: 命令行配置起步
          url: /config-guide/cli/config-cli-subcommands.html

        - label: 管理缓存
          url: /config-guide/cli/config-cli-subcommands-cache.html

        - label: 管理索引
          url: /config-guide/cli/config-cli-subcommands-index.html

        - label: 配置和执行定时任务
          url: /config-guide/cli/config-cli-subcommands-cron.html

        - label: 代码编译器
          url: /config-guide/cli/config-cli-subcommands-compiler.html

        - label: 设置Magento的模式
          url: /config-guide/cli/config-cli-subcommands-mode.html

        - label: 统一资源名称(URN)高亮
          url: /config-guide/cli/config-cli-subcommands-urn.html

        - label: 依赖报告
          url: /config-guide/cli/config-cli-subcommands-depen.html

        - label: 配置管理
          versions: ["2.2", "2.3"]
          children:

            - label: 导出配置
              url: /config-guide/cli/config-cli-subcommands-config-mgmt-export.html

            - label: 设置配置值
              url: /config-guide/cli/config-cli-subcommands-config-mgmt-set.html

            - label: 从配置文件导入数据
              url: /config-guide/cli/config-cli-subcommands-config-mgmt-import.html

        - label: 翻译字典和语言包
          url: /config-guide/cli/config-cli-subcommands-i18n.html

        - label: 静态视图文件部署
          children:

            - label: 静态文件部署策略
              versions: ["2.2", "2.3"]
              url: /config-guide/cli/config-cli-subcommands-static-deploy-strategies.html

            - label: 部署静态视图文件
              url: /config-guide/cli/config-cli-subcommands-static-view.html

        - label: 创建软链接到LESS文件
          url: /config-guide/cli/config-cli-subcommands-less-sass.html

        - label: 运行单元测试
          url: /config-guide/cli/config-cli-subcommands-test.html

        - label: 转换布局的XML文件
          url: /config-guide/cli/config-cli-subcommands-layout-xml.html

        - label: 为性能测试生成数据
          url: /config-guide/cli/config-cli-subcommands-perf-data.html

        - label: 运行Magento支持工具 (仅企业版适用)
          url: /config-guide/cli/config-cli-subcommands-spt-util.html

    - label: Magento配置文件
      url: /config-guide/config/config-magento.html
      children:

        - label: Magento的部署配置
          url: /config-guide/config/config-php.html

        - label: 模块配置文件
          url: /config-guide/config/config-files.html

        - label: 创建或扩展配置类型
          url: /config-guide/config/config-create.html

        - label: 禁用模块输出
          versions: ["2.2", "2.3"]
          url: /config-guide/config/disable-module-output.html

        - label: 配置参考
          versions: ["2.1", "2.2", "2.3"]
          children:

            - label: 敏感的和系统特定的
              url: /config-guide/prod/config-reference-sens.html
              versions: ["2.1", "2.2", "2.3"]

            - label: 支付配置路径参考
              url: /config-guide/prod/config-reference-payment.html
              versions: ["2.1", "2.2", "2.3"]

            - label: 其它配置路径参考
              url: /config-guide/prod/config-reference-most.html
              versions: ["2.1", "2.2", "2.3"]

            - label: Magento Commerce for B2B Extension configuration paths reference
              url: /config-guide/prod/config-reference-b2b.html
              versions: ["2.2", "2.3"]

            - label: .gitignore参考
              url: /config-guide/prod/config-reference-gitignore.html
              versions: ["2.2", "2.3"]

            - label: 使用环境变量覆盖配置设置
              url: /config-guide/prod/config-reference-var-name.html
              versions: ["2.1", "2.2", "2.3"]

            - label: config.php参考
              url: /config-guide/prod/config-reference-configphp.html
              versions: ["2.2", "2.3"]

            - label: env.php参考
              url: /config-guide/prod/config-reference-envphp.html
              versions: ["2.2", "2.3"]

    - label: 配置缓存
      url: /config-guide/cache.html
      children:

        - label: 将缓存前端与缓存类型关联
          url: /config-guide/cache/cache-types.html

        - label: 底层缓存选项
          url: /config-guide/cache/cache-options.html

        - label: 静态内容签名
          versions: ["2.2", "2.3"]
          url: /config-guide/cache/static-content-signing.html

    - label: 配置Redis
      url: /config-guide/redis/config-redis.html
      children:

        - label: 使用Redis作为Magento页面缓存和默认缓存
          url: /config-guide/redis/redis-pg-cache.html

        - label: 使用Redis作为Session存储
          url: /config-guide/redis/redis-session.html

    - label: 配置和使用Varnish
      url: /config-guide/varnish/config-varnish.html
      children:

        - label: 安装Varnish
          url: /config-guide/varnish/config-varnish-install.html

        - label: 配置Varnish和你的web服务器
          url: /config-guide/varnish/config-varnish-configure.html

        - label: 配置Magento使用Varnish
          url: /config-guide/varnish/config-varnish-magento.html

        - label: Varnish高级配置
          versions: ["2.2", "2.3"]
          url: /config-guide/varnish/config-varnish-advanced.html

        - label: How Magento cache clearing works with multiple Varnish instances
          versions: ["2.2", "2.3"]
          url: /config-guide/varnish/use-multiple-varnish-cache.html

        - label: 最终校验
          url: /config-guide/varnish/config-varnish-final.html

        - label: 在Varnish下Magento的缓存清除是如何工作的
          url: /config-guide/varnish/use-varnish-cache.html

        - label: Varnish缓存是如何工作的
          url: /config-guide/varnish/use-varnish-cache-how.html

        - label: 排除503错误
          url: /config-guide/varnish/tshoot-varnish-503.html

    - label: 使用memcached做为session存储
      url: /config-guide/memcache/memcache.html
      children:

        - label: 在Ubuntu上安装、配置和验证memcached
          url: /config-guide/memcache/memcache_ubuntu.html

        - label: 在CentOS上安装、配置和验证memcached
          url: /config-guide/memcache/memcache_centos.html

        - label: 配置Magento使用memcached
          url: /config-guide/memcache/memcache_magento.html

    - label: 多站和多店
      url: /config-guide/multi-site/ms_over.html
      children:

        - label: 在管理面板设置多站、多店及网店视图
          url: /config-guide/multi-site/ms_websites.html

        - label: 教程-在nginx下设置多站或多店
          url: /config-guide/multi-site/ms_nginx.html

        - label: 教程-在Apache下设置多站或多店
          url: /config-guide/multi-site/ms_apache.html

    - label: 设置自定义的定时任务和任务组(cron)
      url: /config-guide/cron/custom-cron.html
      children:

        - label: 自定义的定时任务和任务组(cron)参考
          url: /config-guide/cron/custom-cron-ref.html

        - label: 配置自定义的定时任务和任务组(cron)(教程)
          url: /config-guide/cron/custom-cron-tut.html

    - label: 配置数据库分析器
      url: /config-guide/db-profiler/db-profiler.html

    - label: 安装和配置Elasticsearch (仅企业版适用)
      versions: ["2.1","2.2", "2.3"]
      url: /config-guide/elasticsearch/es-overview.html
      children:

        - label: 配置nginx和Elasticsearch
          url: /config-guide/elasticsearch/es-config-nginx.html

        - label: 配置Apache和Elasticsearch
          url: /config-guide/elasticsearch/es-config-apache.html

        - label: 配置Elasticsearch停用词
          url: /config-guide/elasticsearch/es-config-stopwords.html

        - label: 配置Magento使用Elasticsearch
          url: /config-guide/elasticsearch/configure-magento.html

    - label: 消息队列 (仅企业版适用)
      url: /config-guide/mq/rabbitmq-overview.html
      children:

        - label: 管理消息队列
          url: /config-guide/mq/manage-mysql.html


    - label: Install and configure Solr (仅企业版适用)
      versions: ["2.0","2.1"]
      url: /config-guide/solr/solr-overview.html
      children:

        - label: Configure Solr and Magento
          url: /config-guide/solr/solr-magento.html

        - label: Prepare Solr for production
          url: /config-guide/solr/solr-script.html

    - label: 数据库分库执行方案(仅企业版)
      url: /config-guide/multi-master/multi-master.html
      children:

        - label: 自动配置主数据库
          url: /config-guide/multi-master/multi-master_masterdb.html

        - label: 手动配置主数据库
          url: /config-guide/multi-master/multi-master_manual.html

        - label: 数据库分库验证
          url: /config-guide/multi-master/multi-master_verify.html

        - label: 设置可选数据库复制
          url: /config-guide/multi-master/multi-master_slavedb.html

    - label: 自定义日志
      url: /config-guide/log/log-intro.html
      children:

        - label: Magento日志的更多细节
          url: /config-guide/log/log-magento.html

        - label: 示例 - 记录数据库活动日志
          url: /config-guide/log/log-db.html

    - label: 如何定位你的session文件
      url: /config-guide/sessions.html

    - label: 部署Magento到生产环境
      url: /config-guide/prod/prod.html
      versions: ["2.0","2.1"]
      children:

        - label: Magento ownership and permissions in development and production
          url: /config-guide/prod/prod_file-sys-perms.html

        - label: 部署到生产环境
          url: /config-guide/prod/prod_deploy.html

        - label: 单机部署
          url: /config-guide/prod/single-machine-deployment.html

    - label: Optimization
      versions: ["2.0", "2.1"]
      children:
        - label: Magento Optimization Guide
          url: /config-guide/prod/prod_perf-optimize.html
        - label: 开发环境推荐
          versions: ["2.1"]
          url: /config-guide/prod/development-environment.html
